# Site settings
title: Rubbx WriteUps
SEOTitle: Rubbx WriteUps
header-img: img/home-bg-art.jpg
email:
description: "Hacking is Life"
keyword: ""
url: "http://rubbxalc.github.io"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:
csdn_username:
github_username: rubbxalc
twitter_username:  _rbbx_
jianshu_username:
#sv_username: study-articulo
linkedin_username:  rubén-alcántara-58bb08234/



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: #rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
plugins: [jekyll-paginate, jekyll-analytics, jekyll-sitemap]

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
#duoshuo_username:
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# LiveRe setttings
#livere_uid:

# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: G-0B6FKK50WG          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking


# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Rubén Alcántara" 
sidebar-avatar: /img/avatar-wb.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

sass:
  sass_dir: /assets/_sass
  style: :compressed
collections:
  articulos:
    output: true
    permalink: /:path/
defaults:
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post

friends: [
    {
        title: "HackTheBox",
        href: "https://app.hackthebox.com/users/1114368"

    },
    {
        title: "HackMyVM",
        href: "https://hackmyvm.eu/public/?u=rubbx"

    },
    {
        title: "Youtube",
        href: "https://www.youtube.com/channel/UCNK4GwiaIDxyO3Sd1CD7Tow"

    },
    {
        title: "Twitch",
        href: "https://www.twitch.tv/rubbx_"

    },
    {
        title: "GitBook",
        href: "https://rubbx.gitbook.io/notes/"

    }
]
